spring.application.name=CourtTime
spring.datasource.url=${COURTTIME_DB_URL:jdbc:postgresql://localhost:5432/courttime}
spring.datasource.username=${COURTTIME_DB_USERNAME:postgres}
spring.datasource.password=${COURTTIME_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
